### PR TITLE
Add corrections to meet the official requirements

### PR DESCRIPTION
**Pull request by geokats**
I have added some small corrections that were required by the department when I submitted my thesis.
More specifically:
- When keywords take more than one row, the second row must start at the same point as the first
- Fix table of contents sizes and alignment
- The size of the bibliography references must be arial 10
- Acronyms table must have a complete grid
- Captions in figures and tables must be centered, bold, arial 10

### CODE REVIEW

**Review by errikos — APPROVED** [review]
Thanks for the contribution, this looks good!

**Review by errikos — CHANGES_REQUESTED** [review]
In fact, could you add a revision entry in https://github.com/errikos/dithesis/blob/master/dithesis.cls#L49 ?

**Comment by geokats** [comment]
> In fact, could you add a revision entry in https://github.com/errikos/dithesis/blob/master/dithesis.cls#L49 ?

Nice idea! I have added another commit!

**Review by errikos — APPROVED** [review]
Thanks!

**Pull request merged**
